name: Deploy and test dev

on:
  pull_request:
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Checkout UI
        uses: actions/checkout@v2
      - name: Build UI and publish timestamped Docker image
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: hsldevcom/transitlog-ui
          username: ${{ secrets.TRANSITLOG_DOCKERHUB_USER }}
          password: ${{ secrets.TRANSITLOG_DOCKERHUB_TOKEN }}
          buildargs: BUILD_ENV=dev
          tags: date-${{ steps.date.outputs.date }}
      - name: Build UI and publish Docker image
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: hsldevcom/transitlog-ui
          username: ${{ secrets.TRANSITLOG_DOCKERHUB_USER }}
          password: ${{ secrets.TRANSITLOG_DOCKERHUB_TOKEN }}
          buildargs: BUILD_ENV=dev
          tags: dev
  test-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Check out PR code
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: "20"
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run Cypress tests against dev
        uses: cypress-io/github-action@v7
        with:
          install: false
        env:
          CYPRESS_BASE_URL: https://dev.reittiloki.hsldev.com
          configFile: dev

